name: abinbev
recipe: drupal11
config:
  webroot: web

services:
  database:
    type: mariadb:10.6
    portforward: true
    creds:
      user: abinbev
      password: abinbev
      database: abinbev
